### ISSUE TITLE
Reindeer Render Crash

### ISSUE THREAD

**Issue by mahjerion** [itsmeow/betteranimalsplus#269]
## Describe what you were doing before the crash

loading into the game, I think.

## To Reproduce

Steps to reproduce the behavior (if possible):
player joined and crashed, probably a reindeer nearby

## Crash Log (REQUIRED)

[crash-2021-11-05_13.36.48-client.txt](https://github.com/itsmeow/betteranimalsplus/files/7487283/crash-2021-11-05_13.36.48-client.txt)

## Versions
- Minecraft Version:v 1.16.5
- Architectury API Version: 1.24.35
- Platform (Forge/Fabric): forge
- Forge Version: 36.2.8
- Fabric Loader Version:
- Fabric API Version:
- Mod Version: 10.2.0

## Additional context
I'm the pack dev, just reporting what my players experienced so I do't have too many deets. if you need more I can ask them!

**Comment by itsmeow** [comment]
More than likely some type of coremod interference, most suspicious culprit would be performant, we've had a lot of issues with performant. I've never seen this crash anywhere else - it seems tied to the model-variant system being bypassed by a mixin or something.

**Comment by She-leap** [comment]
I'm also getting a crash with reindeer, this time on 1.18.1 fabric.
https://pastebin.com/fewdJ8e4

**Comment by itsmeow** [comment]
@BloxcastJason If you could open a separate issue for me, that's a very different crash. Thanks for reporting.

**Comment by itsmeow** [comment]
@BloxcastJason Nevermind, see #275

**Comment by itsdinkd** [comment]
Also happens to my modpack another quality modpack 2 on fabric 1.18.1 using 
betteranimalsplus-1.18.1-11.0.1-fabric.jar

https://paste.corebot.dev/suquhoxeba.md

**Comment by itsmeow** [comment]
@red2blue You need to generate a client config and that should prevent the crash. Just load into a singleplayer world at least once before joining a server. Issue has been fixed in development, will be released soon. See #275.

**Comment by itsdinkd** [comment]
I already have the client config that I distribute in the pack, that definitely does not fix it.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/147804155-733aef12-c114-4314-a93b-e94d2193f482.png)
![image](https://user-images.githubusercontent.com/35115304/147804160-0a0e23f6-5ea0-4c1f-b5cb-ed0694bc471b.png)

This is putting players in a crash loop due to them rejoining when it is still existing in their world. Since its fixed in that commit, I would really appreciate it if you have the time to release a hotfix on cursefurge so i can update the modpack asap.

**Comment by itsmeow** [comment]
@red2blue @BloxcastJason Fixes for your crash have been released.

**Comment by itsdinkd** [comment]
> @red2blue @BloxcastJason Fixes for your crash have been released.

Thank you so much <3 happy new years.

**Comment by itsmeow** [comment]
No one has seemed to reproduce a crash like this one, and it looks to be caused by another mod, so I will be closing this.
